Set up testing env

diff --git a/dev/start b/dev/start
--- a/dev/start
+++ b/dev/start
@@ -1,6 +1,10 @@
 #!/usr/bin/env bash
 
-set -eo pipefail
+set -xeo pipefail
+
+# CC servers can't find it for some reason.  Local shellcheck is fine.
+# shellcheck disable=SC1091
+source "./keycloak/keycloak_functions.sh"
 
 # Navigate to the dev directory (where this script lives) to ensure we can run this script
 # from anywhere.
@@ -9,7 +13,17 @@ cd "$(dirname "$0")"
 # TODO: add a prompt and an -f flag to give the user control over destroying an already existing development environment.
 # It can be such a pain to mistakenly destroy your environment.
 
+ENABLE_AUTHN_OIDC=false
+
+# Minimal set of services.  We add to this list based on cmd line flags.
+services=(pg conjur cli-dev)
+
+default_authenticators="authn"
+enabled_authenticators="$default_authenticators"
+
 main() {
+  parse_options "$@"
+
   if docker-compose ps conjur | grep conjur >/dev/null 2>&1; then
     ./stop
   fi
@@ -55,8 +69,7 @@ EOL
 
   echo
   echo "Starting Containers"
-  docker-compose up -d
-
+  docker-compose up -d --no-deps "${services[@]}"
 
   echo
   docker-compose exec -T pg bash -e <<EOL
@@ -73,7 +86,7 @@ exit 1
 EOL
 
   echo
-  docker-compose exec conjur conjurctl wait
+  wait_for_conjur
 
   echo
   echo 'Setting up Conjur...'
@@ -91,6 +104,14 @@ EOL
   echo "Loading policy"
 
   docker-compose exec -T conjur conjurctl policy load dev /dev/stdin < policy.yml
+
+  echo
+  echo "Setting up authenticators"
+
+  init_oidc
+
+  # Updates CONJUR_AUTHENTICATORS and restarts required services.
+  start_auth_services
   
   echo
   echo "Entering CLI container"
@@ -99,6 +120,147 @@ EOL
 
   echo
   docker-compose exec cli-dev bash
+}
+
+parse_options() {
+  while true ; do
+    case "$1" in
+      --authn-oidc ) ENABLE_AUTHN_OIDC=true ; shift ;;
+      # -h | --help ) print_help ; shift ;;
+       * )
+         if [ -z "$1" ]; then
+           break
+         else
+           echo "$1 is not a valid option"
+           exit 1
+         fi ;;
+    esac
+  done
+}
+
+start_conjur_server() {
+  echo "Starting Conjur server"
+  docker-compose exec -d conjur conjurctl server
+
+  echo 'Checking if Conjur server is ready'
+  wait_for_conjur
+}
+
+wait_for_conjur() {
+  docker-compose exec conjur conjurctl wait
+}
+
+client_load_policy() {
+  local policy_file=$1
+
+  docker-compose exec -T cli-dev conjur policy load -b root -f - < "$policy_file"
+}
+
+client_add_secret() {
+  local variable=$1
+  local value=$2
+
+  docker-compose exec cli-dev conjur variable set -i "$variable" -v "$value"
+}
+
+configure_oidc_providers() {
+  # Start conjur again, since it is recreating by docker-compose because of
+  # dependency with keycloak
+  start_conjur_server
+  wait_for_keycloak_server
+  fetch_keycloak_certificate
+  configure_oidc_authenticators
+  enable_oidc_authenticators
+  create_keycloak_users
+  echo "keycloak admin console url: http://0.0.0.0:7777/auth/admin"
+}
+
+configure_oidc_authenticators() {
+  # add variables' values for keycloak
+  echo "Setting keycloak variables values in conjur"
+
+    client_load_policy "keycloak/policy.yml"
+
+    client_add_secret 'conjur/authn-oidc/keycloak/provider-uri' 'https://keycloak:8443/auth/realms/master'
+    client_add_secret 'conjur/authn-oidc/keycloak/client-id' 'conjurClient'
+    client_add_secret 'conjur/authn-oidc/keycloak/client-secret' '1234'
+    client_add_secret 'conjur/authn-oidc/keycloak/claim-mapping' 'email'
+    client_add_secret 'conjur/authn-oidc/keycloak/nonce' 'af88d8f8ff6631fb4cf0'
+    client_add_secret 'conjur/authn-oidc/keycloak/state' 'd38e57e0fd47ccffa9c2'
+    client_add_secret 'conjur/authn-oidc/keycloak/redirect_uri' 'http://localhost:8888/callback'
+
+    client_load_policy "keycloak/users.yml"
+
+
+
+  # if [[ $ENABLE_OIDC_OKTA = true ]]; then
+  #   # Specific for new OIDC Authenticator
+  #   client_load_policy '/src/conjur-server/dev/policies/authenticators/authn-oidc/okta-2.yml'
+  #   client_add_secret 'conjur/authn-oidc/okta-2/provider-uri' 'https://dev-92899796.okta.com/oauth2/default'
+  #   client_add_secret 'conjur/authn-oidc/okta-2/client-id' '0oa3w3xig6rHiu9yT5d7'
+  #   client_add_secret 'conjur/authn-oidc/okta-2/client-secret' 'e349BMTTIpLO-rPuPqLLkLyH_pO-loUzhIVJCrHj'
+  #   client_add_secret 'conjur/authn-oidc/okta-2/claim-mapping' 'preferred_username'
+  #   client_add_secret 'conjur/authn-oidc/okta-2/nonce' '1656b4264b60af659fce'
+  #   client_add_secret 'conjur/authn-oidc/okta-2/state' '4f413476ef7e2395f0af'
+  #   client_add_secret 'conjur/authn-oidc/okta-2/redirect_uri' 'http://localhost:3000/authn-oidc/okta-2/cucumber/authenticate'
+
+  #   client_load_policy '/src/conjur-server/dev/policies/authenticators/authn-oidc/okta-users.yml'
+  # fi
+}
+
+enable_oidc_authenticators() {
+  echo "Configuring Keycloak as OpenID provider for automatic testing"
+  # We enable an OIDC authenticator without a service-id to test that it's
+  # invalid.
+  enabled_authenticators="$enabled_authenticators,authn-oidc/keycloak"
+
+  # if [[ $ENABLE_OIDC_OKTA = true ]]; then
+  #   echo "Configuring OKTA as OpenID provider for manual testing"
+  #   enabled_authenticators="$enabled_authenticators,authn-oidc/okta,authn-oidc/okta-2"
+  # fi
+}
+
+init_oidc() {
+  # # ADFS and OKTA make no sense without OIDC.
+  # if [[ $ENABLE_AUTHN_OIDC = false &&
+  #   ($ENABLE_OIDC_ADFS = true || $ENABLE_OIDC_OKTA = true) ]]
+  # then
+  #   echo "Error: --oidc-adfs and --oidc-okta both require --authn-oidc"
+  #   exit 1
+  # fi
+
+  if [[ $ENABLE_AUTHN_OIDC != true ]]; then
+    return
+  fi
+
+  services+=(keycloak)
+  docker-compose up -d --no-deps "${services[@]}"
+
+  configure_oidc_providers
+
+  # if [[ $ENABLE_AUTHN_LDAP = true && $ENABLE_OIDC_OKTA = true ]]; then
+  #   echo "Building & configuring Okta-LDAP agent"
+  #   services+=(okta-ldap-agent)
+  #   docker-compose up -d --no-deps "${services[@]}"
+
+  #   echo "Starting Okta agent service"
+  #   docker exec "$(docker-compose ps -q okta-ldap-agent)" \
+  #     "/opt/Okta/OktaLDAPAgent/scripts/OktaLDAPAgent"
+  # fi
+}
+
+start_auth_services() {
+  echo "Setting CONJUR_AUTHENTICATORS to: $enabled_authenticators"
+  env_args+=(-e "CONJUR_AUTHENTICATORS=$enabled_authenticators")
+
+  # Will restart services if configuration has changed.  I think this happens
+  # when additional authenticators are enabled.
+  docker-compose up -d --no-deps "${services[@]}"
+
+  # If that happens, we need to restart Conjur server.
+  if [[ "$enabled_authenticators" != "$default_authenticators" ]]; then
+    start_conjur_server
+  fi
 }
 
 main "$@"
